name: Docker SwarmKit (Embedded)
description: >
  A toolkit for orchestrating distributed systems at any scale (Docker 1.12+ only)
version: v1.12
category: Orchestration
maintainer: james@rancher.com
minimum_rancher_version: 1.1.3