name: Docker SwarmKit
description: >
  A toolkit for orchestrating distributed systems at any scale
version: v1.12.0
category: Orchestration
maintainer: james@rancher.com
minimum_rancher_version: 1.1.3