version: '2'
services:
  swarmkit:
    image: llparse/swarmkit:v1.13.0-beta.2
    environment:
      MANAGER_SCALE: ${MANAGER_SCALE}
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.dns: 'true'
      io.rancher.container.pull_image: always
    network_mode: host
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
