.catalog:
  version: v1.13.0-beta.2
  minimum_rancher_version: 1.2.2
  questions:
  - variable: MANAGER_SCALE
    label: Number of Managers
    description: Desired number of managers to participating in service orchestration. This dictates host resilience.
    required: true
    default: 3
    type: int
