swarm-mgr:
    image: cloudnautique/swarm-mgr:v0.3.0-bill-01
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash
    labels:
        io.rancher.scheduler.global: true
        io.rancher.sidekicks: healthcheck,docker-socket
docker-socket:
    image: cloudnautique/swarm-mgr:v0.3.0-bill-01
    net: "container:swarm-mgr"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    stdin_open: true
    tty: true
    command: /socat.sh
healthcheck:
    net: "container:swarm-mgr"
    image: cloudnautique/swarm-mgr:v0.3.0-bill-01
    command: /giddyup health 
