swarm-mgr:
    image: cloudnautique/swarm-mgr:v0.2.0
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    stdin_open: true
    tty: true
    labels:
        io.rancher.scheduler.global: true
