swarmkit-mon:
  image: llparse/swarmkit:v1.12
  labels:
    io.rancher.container.agent.role: environment
    io.rancher.container.create_agent: 'true'
    io.rancher.container.dns: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: io.rancher.host.docker_version=1.12
    io.rancher.scheduler.global: 'true'
  net: host
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock