swarm-mgr:
    image: cloudnautique/swarm-mgr:v0.2.1-bill-4
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    stdin_open: true
    tty: true
    labels:
        io.rancher.scheduler.global: true
        io.rancher.sidekicks: healthcheck
healthcheck:
    net: "container:swarm-mgr"
    image: cloudnautique/swarm-mgr:v0.2.1-bill-4
    command: /giddyup health 
