.catalog:
  version: v1.12
swarmkit-mon:
  health_check:
    request_line: GET /ping HTTP/1.0
    port: 2378
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 1
    unhealthy_threshold: 2